/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.util.List;
import model.AcceptingHandler;
import model.CompleteHandler;
import model.CookingHandler;
import model.FoodOrder;
import model.HandOverToDriverHandler;
import model.ManageOrders;
import model.OrderManagementGroup;
import model.OrderStepHandler;
import model.Orders;
import model.PackingHandler;

/**
 *
 * @author nimsa
 */
public class ManageOrder extends javax.swing.JPanel {

    private OrderManagementGroup managementGroup;
    private ManageOrders order_panel;

    private AcceptingHandler acceptingHandler;
    private CookingHandler cookingHandler;
    private PackingHandler packingHandler;
    private HandOverToDriverHandler handOverToDriverHandler;
    private CompleteHandler completeHandler;

    private Orders orders;

    private List<FoodOrder> orderList;

    /**
     * Creates new form ManageOrder
     */
    public ManageOrder(List<FoodOrder> orderList, OrderManagementGroup managementGroup) {
        initComponents();
        this.orderList = orderList;
        this.managementGroup = managementGroup;

        orders = new Orders(orderList);

        createHander();
    }

    public void createHander() {
        acceptingHandler = new AcceptingHandler();
        cookingHandler = new CookingHandler();
        packingHandler = new PackingHandler();
        handOverToDriverHandler = new HandOverToDriverHandler();
        completeHandler = new CompleteHandler();

        acceptingHandler.setHanler(cookingHandler);
        cookingHandler.setHanler(packingHandler);
        packingHandler.setHanler(handOverToDriverHandler);
        handOverToDriverHandler.setHanler(completeHandler);

        acceptingHandler.setOrder_gui(this);
        cookingHandler.setOrder_gui(this);
        packingHandler.setOrder_gui(this);
        handOverToDriverHandler.setOrder_gui(this);
        completeHandler.setOrder_gui(this);

        process(orders);
    }

    public void process(Orders orders) {
        acceptingHandler.handleOrder(orders);
    }

    public void displayAccepting(Orders orders) {
        order_panel = new ManageOrder_Accept(orders, managementGroup, this);
        display();
    }

    public void displayCooking(Orders orders) {
        order_panel = new ManageOrder_Cook(orders, managementGroup, this);
        display();
    }
    
    public void displayPacking(Orders orders) {
        order_panel = new ManageOrder_Pack(orders, managementGroup, this);
        display();
    }
    
    public void displayHandOver(Orders orders) {
        order_panel = new ManageOrder_HandOver(orders, managementGroup, this);
        display();
    }
    
        public void displayCompleted(Orders orders) {
        order_panel = new ManageOrder_Completed(orders, managementGroup, this);
        display();
    }

    public void display() {
        jPanel5.removeAll();
        jPanel5.add(order_panel);
        jPanel5.repaint();
        jPanel5.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(524, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(524, 300));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Manage Order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addContainerGap(503, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(14, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addContainerGap(498, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 48, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
